### ISSUE TITLE
Propose versioning scheme/policy for `yagna-integration`

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/goth#123]
Propose how to version various artifacts produced from stuff in the `yagna-integration` repository.

## Things that need versioning
* docker image `api-monitor`
* python package (with yet unspecified but cool name) with test harness
* exception: may use a version (including commit SHA) from `yagna.deb` for the `yagna` image, at least for the time being 

## Requirements
* A version number should identify a unique commit (in the main branch)
* We should be able to automate at least checking that the version is bumped on each commit to the main branch (if not to bump the version automatically)

## Possible solutions
* standard `x.y.z` version number, following semantic versioning, stored in `setup.py`
  - `y` can become high
* `x.y.z.v`, with `x.y.z` as above and `v` the number of commits since the most recent tag
  - `x.y.z` stored in `setup.py`, `v` computed by a script
* commit SHA
  - hard to read and memorize
* `x.y.z+g<SHA>`
  - use `git describe` to produce the version

## Our choice
* `x.y.z-<#commits-since-tag>-g<SHA[:8]>`, for example `0.21.0-777-gaa142bc10`
  - think of changing the .deb version to this format
  - use `git describe` to produce the version (`git describe --tags --abbrev=8 --match %s[0-9]*` or smth like that)

# The Workflow
* After merging a PR into the main branch, the author of the PR adds a new tag for the merge commit in the semver format `x.y.z`, following the semver semantics (www.semver.org).

# TODO:
- tag `api-monitor` image with version, in a python code in the pytest fixture that builds the image
- modify `setup.py` to set version of the resulting python package (based on the output of `git describe`)

**Comment by stranger80** [comment]
...is this still relevant, or can we close this?

**Comment by azawlocki** [comment]
@stranger80 I think we may close this. For the `goth` package we (will) use semantic versioning. Docker images built by `goth` are managed by `goth`, I don't think we should introduce any versioning scheme for them. @zakaprov what do you think?

**Comment by stranger80** [comment]
Closing, after comment from @azawlocki.
