### ISSUE TITLE
Create integration tests for the API Monitor

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/goth#125]
Thing to test:
- Run the API Monitor in a docker container
- Send a couple of requests, make sure the monitor logs those requests
- Add some sample assertions referring to the test requests and make sure they succeed/fail as expected

**Comment by stranger80** [comment]
...should this be moved to Done?

**Comment by azawlocki** [comment]
@stranger80 It's unlikely we'll ever have time to work on this as a separate task. Hopefully the API Monitor will be used in integration tests in various projects from the `yagna` ecosystem and that would provide many opportunities to also test the monitor itself.
