### ISSUE TITLE
Replace requestor agent with a test scenario using activity, market and payment APIs

### ISSUE THREAD

**Issue by zakaprov** [golemfactory/goth#139]
Requestor probe introduced in #133 still relies on running the requestor agent as an external process in the daemon's Docker container.

Since the requestor probe includes clients for the daemon APIs (activity, market and payment), the requestor agent process should be replaced with a test scenario within the test harness. See the level 1 [demo test case](https://github.com/golemfactory/yagna-integration/blob/6421bc4043bab7b838fdf3c8192d0dd5ff6629af/docs/demo_test_case_draft.txt) to get an idea of what this scenario could look like.

The parts of code which should be removed from the `RequestorProbe` class have been marked with a `TODO` comment.

**Comment by stranger80** [comment]
...should this be moved to Done?
