### ISSUE TITLE
Improve building node topologies for test scenarios

### ISSUE THREAD

**Issue by zakaprov** [golemfactory/goth#168]
In the context of this project, topology is a list which specifies the nodes to be started for a test, along with their configuration. Here's an example of such a list:
https://github.com/golemfactory/yagna-integration/blob/ad793e6893c200bfc7bd0f8743830ff6af9558e7/test/level0/test_level0.py#L99-L128

Currently, the process of defining a topology is quite verbose with no helpers available. This means that a fairly common scenario of starting a number of identical providers for a test would require the test author to implement it manually, including taking care of providing environment and volumes for the containers.

I think it would make sense to create a builder for the topology which could help automate the repetitive parts. Here's a rough sketch of what I have in mind:
```
builder = TopologyBuilder()
builder.add_many(count=10, role=Role.Provider, use_proxy=True)
builder.add(name="custom_requestor", role=Role.Requestor, environment={...})

topology: List[YagnaContainerConfig] = builder.build()
```

**Comment by stranger80** [comment]
...is this Done? or still relevant?
