### ISSUE TITLE
Enable VM ExeUnit testing in TestHarness

### ISSUE THREAD

**Issue by stranger80** [golemfactory/goth#226]
Testing the VM ExeUnit inside docker may be problematic (as it would require nested virtualization).
- Research the way to run VM ExeUnit test cases under TestHarness.

**Comment by zakaprov** [comment]
Support for VM tests has been added in #324 and since https://github.com/golemfactory/goth/pull/339 we're using a self-hosted runner in Actions, enabling those tests in CI. I believe the issue is now resolved.
