### ISSUE TITLE
Use ghapi in GithubDownloader

### ISSUE THREAD

**Issue by zakaprov** [golemfactory/goth#384]
[ghapi](https://ghapi.fast.ai/) provides an up-to-date, generated interface for the entire GitHub API, complete with pagination support. This library could be utilized in the [`GithubDownloader`](https://github.com/golemfactory/goth/blob/ff44ed782e55cfcb4d44c4030fe19ac398978fcf/goth/runner/download/__init__.py#L37) class which currently relies on manually-built requests to the API.

**Comment by pradeepbbl** [comment]
hi, would like to pick this up if no objection

**Comment by zakaprov** [comment]
Hey there! Sure, go ahead. We do not have a contributor's guide for this repo just yet, so feel free to reach out should you have any questions.

**Comment by pradeepbbl** [comment]
please review the MR and let me know if I miss anything or did something wrong :)
