### ISSUE TITLE
Create provider probe class with API capabilities

### ISSUE THREAD

**Issue by zakaprov** [golemfactory/goth#427]

**Comment by pnowosie** [comment]
You might find worth to uncomment [these lines](https://github.com/golemfactory/goth/blob/491f30a52c733917a528a73abb33550063c8a71b/test/yagna/module/payments/test_zero_amount_txs.py#L142-L144) as a test of the functionality 😉

**Comment by stranger80** [comment]
...should this be moved to Done?

**Comment by zakaprov** [comment]
Not yet, though I just realised I created a duplicate in #433 with some more details on the issue. I'm closing this one in favour of #433.
