### ISSUE TITLE
Improve test error reporting

### ISSUE THREAD

**Issue by zakaprov** [golemfactory/goth#517]
Currently, many test failures may be difficult to debug for users who have little or no context about `goth`'s internals (excessive tracebacks, side-effect failures obscuring the actual problems etc.).
This issue covers better identifying these pain points, as well as trying to address at least some of them. This could be done by either introducing more specific error types and/or adding some hints for the user (e.g. "take a look at the test run logs for more information").

**Comment by tworec** [comment]
First aproach will be to swallow all of the tracebacks, as they usually seems not to be informative/useful, and display only ERROR in logs. Tracebacks will still be accessible within the log files.

The action is primarily on @zakaprov and then we can gather again within goth working group to discuss it further.
