### ISSUE TITLE
goth interactive mode fails on docker-py "409 Client Error: Conflict for url"

### ISSUE THREAD

**Issue by pryce-turner** [golemfactory/goth#593]
I was running goth interactively without any issues. After a couple week hiatus I've tried running it again without changing anything (I think). I also started from scratch on a brand-new VM and can reproduce the behavior. I'll also note that changing the compose file in goth-config.yml from the default `docker-compose.yml` to `docker-compose-hybrid-net.yml` resolves the issue and leads to a normal startup. However, since I don't know the difference between the 2 modes I can't say if it's an equivalent goth environment - although I have run the hello-world requestor on it, which suggests it's working correctly.

## Steps to reproduce:
- docker login docker.pkg.github.com -u (username)
- export GITHUB_API_TOKEN=(token)
- git clone https://github.com/golemfactory/goth.git
- cd goth
- poetry install
- poetry run poe interactive

## Expected result:
Goth starts up fine and shows `Local goth network ready!`

## Actual result:
Goth fails when starting probes, claiming an API error (from docker-py). The conflict suggests it may be trying to spin up a container that already exists - but I can't know for sure without doing some more digging. Happy to investigate further if this issue is not immediately obvious to someone with more knowledge.

I've attached the logs for the errant run below:
[runner.log](https://github.com/golemfactory/goth/files/9458249/runner.log)

**Comment by pryce-turner** [comment]
Also - I'm able to run my requestor without issue on devnet-beta. If I run it on goth using the `hybrid-net` template I get the below error. Not sure if's related but thought I'd include it..

`[2022-08-31T04:51:45.311+0000 WARNING yapapi.summary] [Job 1] Worker for provider 'provider-1' failed; reason: (-32000, 'Bad content: Flexbuffer Read Error: InvalidRootWidth', {'jsonrpc': '2.0', 'id': 207145055893058858, 'error': {'code': -32000, 'message': 'Bad content: Flexbuffer Read Error: InvalidRootWidth'}})`

**Comment by nieznanysprawiciel** [comment]
Thanks for reporting this problem.
Interactive goth uses latest RC published instead of latest stable release. Since defaults were changed in yagna `pre-rel-v0.11.0-rc7`, this caused incompatibility between docker environments used.

We are working to fix the problem
https://github.com/golemfactory/goth/pull/595

**Comment by pryce-turner** [comment]
Awesome - I'll keep an eye on that PR. Thank you for addressing this issue so quickly!

**Comment by shadeofblue** [comment]
https://github.com/golemfactory/goth/pull/595 merged and released in `goth 0.13.0`: 

https://github.com/golemfactory/goth/releases/tag/0.13.0

**Comment by shadeofblue** [comment]
@pryce-turner please have a look and reopen if you still experience issues

**Comment by pryce-turner** [comment]
@shadeofblue - thanks for the quick fix and merge! It is now starting up correctly but I'm getting a lot of the following right before "goth network ready":

`WARNING  [goth.runner.cli.base] Expected a typing.List but command returned: {'headers': ['name', 'key', 'id', 'role', 'created'], 'values': [['key_3395902370294d96a28b0b0a7c671799.json', '129a41ca3c024b809e76b325147c4f04', '0x17ec8597ff92c3f44523bdc65bf0f1be632917ff', 'manager', '2022-09-06T21:49:12.271808984']]}`

Are these safe to ignore?
