### ISSUE TITLE
[SPIKE] Ignoring some yagna releases

### ISSUE THREAD

**Issue by pwalski** [golemfactory/goth#619]
`goth` should ignore some `yagna` releases when using `use-prerelease` option.
This PR https://github.com/golemfactory/yagna/tree/pwalski/preview_release_prefix makes possible to build `yagna` release with `preview-` prefix. 
The goal is to make `goth` to ignore `yagna` release with `preview-` prefix.

ToDo:
Make goth  support only tag names matching specific pattern, like the ones starting with `pre-rel-*` and `v*`.
Prefix should be configurable and be preconfigured with a reasonable default value in goth config file from default assets.

**Comment by MrDarthShoe** [comment]
@nieznanysprawiciel  & @pwalski  need to talk with SDK team on how to solve this problem

**Comment by pwalski** [comment]
It got more or less implemented here https://github.com/golemfactory/goth/commit/208f31b7ee831579aadef2440267e811c4538db5
