### ISSUE TITLE
Add deposit support for python allocation APIs

### ISSUE THREAD

**Issue by kamirr** [golemfactory/goth#671]
[ya-py-aioclient](https://github.com/golemfactory/ya-py-aioclient)

## Acceptance criteria
- [ ] Can create an allocation with deposit using patched `ya-py-aioclient`

**Comment by kamirr** [comment]
Blocked by https://github.com/golemfactory/yagna/issues/2844

**Comment by golmek** [comment]
50% blocked. but working on non-blocking part

**Comment by golmek** [comment]
https://github.com/golemfactory/ya_tmp_pyapi
